---
- name: installing a package
  hosts: all
  become: true
  tasks:
  - name: installing a httpd package
    yum:
      name: httpd
      state: present
         
  - name: service 'httpd' start
    service:
      name: httpd
      state: started

  - name: copy file
    copy:
     src: /home/myadmin/index.html
     dest: /var/www/html
     mode: 0666
