---
- name: install a jenkins
  hosts: all
  become: true

  tasks:
  - name: install java
    yum:
     name: java
     state: present

  - name: install wget
    yum:
      name: wget
      state: present

  - name: download jenkins repo
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: adding jenkins key
    rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: install jenkins
    yum:
      name: jenkins
      state: present

  - name: start jenkins service
    service:
      name: jenkins
      state: started 
      enabled: yes


...
